#!/usr/bin/env bash
#
# $Id: ods-write-trust-anchor 90334 2017-10-25 12:54:04Z cgielen $
# $URL: https://svn.uvt.nl/its-unix/systems/metagross/usr/local/sbin/ods-write-trust-anchor $
#
# Copyright 2013-2014 Casper Gielen
# Written for Tilburg University
# License: GPLv2 or later


ZONE="$1"

nosql() {
	egrep -v '^MySQL database' 
}

ANCHORDIR=/var/lib/unbound/anchors/
ANCHOR=$ANCHORDIR/$ZONE
DEBUG=false

mkdir -p $ANCHORDIR
chown unbound:unbound $ANCHORDIR

$DEBUG && echo -n "$ZONE:"
KEYS=$(ods-enforcer key export --zone $ZONE 2>&1 | nosql)

if echo $KEYS | grep -q 'in DB but not repository'; then
	echo "$KEYS"
	echo "HSM-failure or database-corruption, ignoring missing keys..."
	KEYS=$(echo $KEYS | grep -v 'in DB but not repository')
fi

if echo $KEYS | grep -q CKR; then
	echo "$KEYS"
	echo "HSM-failure, aborting... "
	exit 1
fi

if ! echo $KEYS | grep -q DNSKEY; then
	echo "$KEYS"
	echo "HSM-failure, no DNSKEY-found, nothing to do."
	exit 1
fi

echo "$KEYS" > $ANCHOR

if [ ! -s $ANCHOR ]; then
	echo "empty anchor!"
	exit 1
fi

chown unbound:unbound $ANCHOR
if $DEBUG; then
	for id in $(sed  -n  's/.*id = \([[:digit:]]*\).*/\1/p' $ANCHOR); do
		echo -n " $id"
	done
	echo "."
fi
