#!/usr/bin/env bash

# Inspecteer de agenda van OpenDNSSEC en meldt wat er binnenkort gaat gebeuren
# specifiek: overzicht van KSKs die de komende maand moeten worden vervangen

# todo: ods-enforcer rollover list overwegen

# Copyright 2010-2017 Casper Gielen
# Written for Tilburg University
# License: GPLv2 or later

usage() {
	echo "usage: $0 [days (default: 30)]"
	exit 1
}

case "$1" in
	"--help")
		usage
		;;
	*)
		# by default look 30 days into the futue
		lookahead=${1-30}
		# input validation
		echo $lookahead |  egrep -q '^[0-9]+$' || usage
		;;
esac

now=$(date "+%s")
day=$(( 3600 * 24 ))

first="yes"

ods-enforcer key list | tail -n +3 | grep KSK | grep -v ' retire '  \
| while read zone type state transition;
do
	if [ "$transition" == "waiting for ds-" ]; then
		dif=0; # ASAP
	else
		tgt=$(date "+%s" -d "$transition")	# volgende transitie
		dif=$(( ($tgt - $now) / $day ))		# tijd tot trans
	fi

	if [ "$dif" -lt "$lookahead" ]; then
		if [ "$first" == "yes" ]; then		# print header
			printf "%-26s %s\n" "Next transition" "Zone" 
			first="no"
		fi
		printf "%-26s %s\n" "$transition" "$zone"	
	fi
done| sort -n
