#!/usr/bin/env bash

# $Id: ods-dsseen 78114 2016-03-08 12:54:25Z cgielen $
# $URL: https://svn.uvt.nl/its-unix/group/dns/opendnssec/usr/local/sbin/ods-dsseen $
#
# Check if new DSes have been published in DNS and activate them.
# 
# Copyright 2013-2016 Casper Gielen
# Written for Tilburg University
# License: GPLv2 or later

#
# TODO
# - do not use a caching resolver
# - use dig ods-ksmutil in batch-mode instead of making seperate calls for each zone
# - match on CKAID instead of keytag
#

# Config
KSMUTIL="ods-ksmutil"
DIG="dig"

usage() {
	echo "usage: $0 [--activate|--force|--quiet|--help] <zone|...>" 
	echo "Check if all DS-records are available through DNS and (optionally) activate the key."
	echo "--help         Display this help text."
	echo "--activate     Activate the key if the DS is found."
	echo "--force        Force activation of keys that are not available (implies --activate)."
	echo "--quiet        Surpress output."
	echo "--all          Apply to all zones with outstanding DSes."
	echo "--really-all   Apply to all zones, required or not."
	exit -1
}

nosql() {
	egrep -v '^MySQL database' 
}

# echo string with datetime prepended
echo_time() {
  echo `date --iso-8601=seconds` $1
}


# get OpenDNSSEC version
ods_version() {
	$KSMUTIL --version | cut -d ' ' -f 3
}

# TODO
# Eigenlijk moet hier _geen_ /caching/-resolver worden gebruikt.
# formaat: @HOSTNAME of leeg om de default servers te gebruiken
# server="@dns1.uvt.nl"
server="@ns0.tilburg1.surf.net"

activate="no" # do not activate by default
quiet="no"    # be verbose by default
force="no"    # only activate keys that are really available
zones=""

# cli options
until [ -z "$*" ];
do
	option="$1"
	shift
	case $option in
		-h|--help)     usage ;;
		--activate)    activate="yes" ;;
		--force)       activate="yes" ; force="yes";;
		--quiet)       quiet="yes" ;;
		--all)         zones=$(echo " "; $KSMUTIL key list 2>&1 | nosql | egrep -v 'Keys:|Zone:' | awk '/waiting for ds-seen/ {print $1}' | sort -u);;
		--really-all)  zones=$(echo " "; $KSMUTIL key list 2>&1 | nosql | egrep -v 'Keys:|Zone:' | awk '{print $1}' | sort -u);;
		*)             zones="$zones $option" ;;
	esac
done

if [ -z "$zones" ]; then
	usage
fi

# The location of the column with the keytag in the output of ksm-util
case $(ods_version) in
	1.3*) keytagcol=9 ;;
	1.4*) keytagcol=12 ;;
	*) echo_time "Unknown OpenDNSSEC version, bailing out!"; exit 1 ;;
esac

dns=$(mktemp)
ods=$(mktemp)
for zone in $zones; do
	# Keytags that can be retrieved from DNS
	# dig: 39269 8 2 9EC50E7BBCC4095355A776D6183773197C05F320FDDE87E513022DB9 6A1E2F48
	$DIG +adflag +aaonly  +short -t DS $zone $server | cut -d ' ' -f 1| sort > $dns
	if [ ! -s "$dns" ]; then # $dns should never be empty
		echo_time "warning: no key(s) for $zone found in DNS at all"
	fi

	# Keytags of dnskeys that are 'waiting for ds-seen'
	# ods-ksmutil: mijnuvt.nl  KSK ready  waiting for ds-seen    d3fe6d5bc1ea73bed16d449d42dcf5e7  LocalHSM  39269
	$KSMUTIL key list -v  --zone $zone 2>&1 |nosql | awk -v col=$keytagcol '/waiting for ds-seen/ {print $col}' |sort -u > $ods

	available=$(  comm -12 $ods $dns)
	unavailable=$(comm -23 $ods $dns)

	# activation
	if [ "$activate" == "yes" ]; then
		if [ "$force" == "yes" ]; then
			available=$(cat $ods)
			echo_time "warning: forced activation of key(s) $available:$zone"
		fi
		for keytag in $available; do
			output=$($KSMUTIL key ds-seen --zone $zone --keytag $keytag 2>&1 | nosql)
			if [ "$quiet" == "no" ]; then
				echo_time "$output"
				echo_time "Key $keytag:$zone activated."
			fi
		done
	fi

	# logging
	if [ "$quiet" == "no" ]; then
		if [ -n "$unavailable" ]; then
			echo_time "The key(s) with tag $unavailable:$zone are not present in DNS."
		else
			if [ -n "$available" ]; then
				echo_time "All keys for $zone are present in DNS."
			else
				echo_time "No unactivated keys for $zone found in DNS."
			fi
		fi
	fi
done
rm $dns $ods
